version: '3'
services:
  wp:
    image: "knights007/wordpress:v1.0.0"
    ports:
      - "8000:80"
    environment:
      WORDPRESS_DB_HOST: "devopsinterview.cw7qgk28g9tl.us-east-1.rds.amazonaws.com"
      WORDPRESS_DB_USER: "devopsinterview"
      WORDPRESS_DB_PASSWORD: "d3v0ps-1nt3rv13w"
      WORDPRESS_DB_NAME: "devopsinterview"
  # mysql:
  #   image: "mysql:8.0"
  #   environment:
  #     MYSQL_ROOT_PASSWORD: qwerty